# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4d5442af5e0a0980d2146b5bd0b8fd312ca6b34f1ae13c83f388ab2af87a1d11fd98b6d91baddb0a52c9c40646a27d2fd88c82360e995c0d01305eea04fab70

test:
  secret_key_base: 571e98e0d4ebf81c4e911908b437ab69636313e32d874a899ac303174a6a2145c962b36f3b0d58ea25d79c73bba735720fb11950520b9b235a70c144e557b687

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
